IF NOT EXISTS (SELECT * FROM information_schema.tables WHERE table_schema = 'INSTITUICAO_SISTEMA' AND table_name = 'NOTIFICACOES') THEN
CREATE TABLE INSTITUICAO_SISTEMA.NOTIFICACOES
(
    ID_NOTIFICACAO BIGINT PRIMARY KEY AUTO_INCREMENT,
    MENSAGEM TEXT NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    ALUNO_FK BIGINT NOT NULL,
    FOREIGN KEY (ALUNO_FK) REFERENCES SISTEMA_INSTITUICAO.ALUNOS(ID_ALUNO)
);
END IF;