IF NOT EXISTS (SELECT * FROM information_schema.tables WHERE table_schema = 'INSTITUICAO_SISTEMA' AND table_name = 'DADOS_ENDERECO') THEN
CREATE TABLE INSTITUICAO_SISTEMA.DADOS_ENDERECO
(
    ID_ENDERECO SERIAL PRIMARY KEY,
    RUA VARCHAR(255),
    COMPLEMENTO VARCHAR(255),
    NUMERO VARCHAR(10),
    CEP VARCHAR(10),
    BAIRRO VARCHAR(100),
    CIDADE VARCHAR(100),
    ESTADO VARCHAR(50),
    PAIS VARCHAR(50),
    ATIVO BOOLEAN DEFAULT TRUE
);
END IF;