IF NOT EXISTS (SELECT * FROM information_schema.tables WHERE table_schema = 'INSTITUICAO_SISTEMA' AND table_name = 'DADOS_PESSOAIS') THEN
CREATE TABLE INSTITUICAO_SISTEMA.DADOS_PESSOAIS
(
    ID_DADOS_PESSOAIS INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255),
    SOBRENOME VARCHAR(255),
    CPF VARCHAR(14),
    DATA_NASCIMENTO DATE,
    SEXO VARCHAR(20),
    ESTADO_CIVIL INT,
    NATURALIDADE INT,
    CONTATO_FK INT,
    ENDERECO_FK INT,
    ATIVO BOOLEAN,
    FOREIGN KEY (CONTATO_FK) REFERENCES INSTITUICAO_SISTEMA.DADOS_CONTATO(ID_CONTATO),
    FOREIGN KEY (ENDERECO_FK) REFERENCES INSTITUICAO_SISTEMA.DADOS_ENDERECO(ID_ENDERECO)
);
END IF;