IF NOT EXISTS (SELECT * FROM information_schema.tables WHERE table_schema = 'INSTITUICAO_SISTEMA' AND table_name = 'ALUNOS') THEN
CREATE TABLE INSTITUICAO_SISTEMA.ALUNO
(
    ID_ALUNO BIGINT PRIMARY KEY AUTO_INCREMENT,
    DADOS_PESSOAIS_FK BIGINT NOT NULL,
    FOREIGN KEY (DADOS_PESSOAIS_FK) REFERENCES SISTEMA_INSTITUICAO.DADOS_PESSOAIS(ID_DADOS_PESSOAIS
);
END IF;