IF NOT EXISTS (SELECT * FROM information_schema.tables WHERE table_schema = 'SISTEMA_INSTITUICAO' AND table_name = 'ALUNO') THEN
CREATE TABLE SISTEMA_INSTITUICAO.ALUNO
(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DADOSPESSOAIS_ID INT,
    FOREIGN KEY (DADOSPESSOAIS_ID) REFERENCES SISTEMA_INSTITUICAO.DADOSPESSOAIS(ID)
);
END IF;