IF NOT EXISTS (SELECT * FROM information_schema.tables WHERE table_schema = 'SISTEMA_INSTITUICAO' AND table_name = 'DADOS_CONTATO') THEN
CREATE TABLE SISTEMA_INSTITUICAO.DADOS_CONTATO
(
    ID SERIAL PRIMARY KEY,
    EMAIL VARCHAR(255),
    CONFIRMACAO_EMAIL VARCHAR(255),
    TELEFONE VARCHAR(20),
    TIPOTELEFONE INTEGER,
    ATIVO BOOLEAN DEFAULT TRUE
);
END IF;