IF NOT EXISTS (SELECT * FROM information_schema.tables WHERE table_schema = 'INSTITUICAO_SISTEMA' AND table_name = 'PERMISSOES') THEN
CREATE TABLE INSTITUICAO_SISTEMA.PERMISSOES
(
    ID_PERMISSAO BIGINT AUTO_INCREMENT PRIMARY KEY,
    PERMISSAO VARCHAR(50) NOT NULL UNIQUE
);
END IF;


